spring:
  profiles:
    active:
    - eureka-2
  application:
    name: service-registry
  boot:
    admin:
      client:
        url: http://localhost:9090
    
eureka:
  client:
    service-url:
      defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka
    
---
spring:
  profiles: eureka-1


server:
  port: 8761

eureka:
  instance:
    hostname: eureka1.tacocloud.com
    appname: service-registry

other:
  eureka:
    host: eureka2.tacocloud.com
    port: 8762

---
spring:
  profiles: eureka-2


server:
  port: 8762

eureka:
  instance:
    hostname: eureka2.tacocloud.com
    appname: service-registry

other:
  eureka:
    host: eureka1.tacocloud.com
    port: 8761