spring:
  application:
    name: testclient-service
    
  profiles:
    active:
    - resttemplate
    
  cloud:
    config:      
      uri: http://localhost:8888
      profile: resttemplate
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
          
