taco:
  orders:
    page-size: 2
    
spring:
  data:
    rest:
      base-path: /api
    cassandra:
      keyspace-name: tacocloud
      contact-points:
      - localhost
      schema-action: recreate-drop-unused
      username: cassandra
      password: cassandra
      
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      