server:
  port: 7889
spring:
  application:
    name: consumer_1
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
#input是接收，注意这里不能再像前面一样写output了
          input:
            destination: stream-demo
          myInput:
            destination: my-stream-demo
          myProcessorInput:
            destination: my-stream-demo-processor
          myProcessorOutput:
            destination: my-stream-demo-processor-out