spring:
  data:
    cassandra:
      keyspace-name: cadtcloud
      contact-points:
      - localhost
      schema-action: recreate-drop-unused
      username: cassandra
      password: cassandra
      
  mail:
    host: smtp.163.com
    username: yyyyyyyy
    password: xxxxxxxx
    default-encoding: UTF-8